# Generated by Django 5.2.3 on 2025-09-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='home/')),
                ('sub_banner', models.ImageField(upload_to='home/')),
            ],
        ),
    ]
