# Generated by Django 5.2.3 on 2025-09-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/')),
            ],
            options={
                'verbose_name': 'Dashboard Image',
                'verbose_name_plural': 'Dashboard Images',
            },
        ),
        migrations.CreateModel(
            name='HowItWorksImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/')),
            ],
            options={
                'verbose_name': 'How It Works Image',
                'verbose_name_plural': 'How It Works Images',
            },
        ),
    ]
