# Generated by Django 5.2.3 on 2025-09-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_dashboardimage_howitworksimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='community/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Community Image',
                'verbose_name_plural': 'Community Images',
                'ordering': ['order'],
            },
        ),
    ]
