# Generated by Django 5.2.3 on 2025-09-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_communityimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aboutus/banner/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MissionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aboutus/mission/')),
                ('title', models.CharField(default='Our Mission', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VisionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aboutus/vision/')),
                ('title', models.CharField(default='Our Vision', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
