# Generated by Django 5.2.3 on 2025-09-05 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_aboutusbanner_missionsection_visionsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_white', models.CharField(help_text='First heading line in white', max_length=200)),
                ('heading_green', models.CharField(help_text='Second heading line in green', max_length=200)),
                ('description', models.TextField(help_text='3 lines description. Use <br> for line breaks where needed.')),
                ('image', models.ImageField(upload_to='blog/banner/')),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Main title. Use <br> for line breaks if needed.')),
                ('reading_time', models.CharField(help_text='Example: 5 Mins Read . 20 May 2025', max_length=50)),
                ('image', models.ImageField(upload_to='blog/posts/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='mainapp.blogcategory')),
            ],
        ),
    ]
