# Generated by Django 5.2.3 on 2025-09-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_blogbanner_blogcategory_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='auth_images/')),
            ],
        ),
    ]
